---
before_script:
  - DUNECI_BRANCH_AUTO=0 duneci-install-module -b releases/2.6 https://gitlab.dune-project.org/core/dune-common.git
  - DUNECI_BRANCH_AUTO=0 duneci-install-module -b releases/2.6  https://gitlab.dune-project.org/core/dune-geometry.git
  - DUNECI_BRANCH_AUTO=0 duneci-install-module -b releases/2.6  https://gitlab.dune-project.org/core/dune-grid.git

debian:10  gcc:c++17:
  image: duneci/base:10
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.gcc.c++17}

debian:9--gcc:
  image: duneci/base:9
  script: duneci-standard-test

debian:9--clang:
  image: duneci/base:9
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}

ubuntu:16.04--gcc:
  image: duneci/base:16.04
  script: duneci-standard-test

ubuntu:16.04--clang:
  image: duneci/base:16.04
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}
