---
.common: &common
  script: duneci-standard-test
  artifacts:
    expire_in: 2 years
    reports:
      junit: junit/*.xml
  tags: [duneci]

dune:2.7 gcc-8 C++17:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:2.7-debian-10-gcc-8-17

dune:2.7 gcc-9 C++20:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:2.7-debian-11-gcc-9-20

dune:2.7 clang C++17:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:2.7-debian-10-clang-7-libcpp-17
